version: '3.8'

volumes:
  ipython_history: {}

services:
  # ###########################################################################
  # Database
  # ###########################################################################
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -t 5 -U ctmd_user || false"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=ctmd
      - POSTGRES_USER=ctmd_user
      - POSTGRES_PASSWORD=manager
